// saudiCities.js

export const saudiCities = {
  Riyadh: [
    "Al Bat'ha",
    "Al Deerah",
    "Al Malaz",
    "Al Murabba",
    "Al Olaya",
    "Diplomatic Quarter",
    "Al Naseem",
    "As Sulimaniyah",
    "Al Shemaysi",
    "Al Wurud",
    "King Fahd District",
    "Hittin",
    "Al Aziziyah",
    "Al Badiʿah",
    "Al Qadisiyah",
    "Al Malga",
  ],

  Jeddah: [
    "Al Murjan",
    "Al Basateen",
    "Al Mohamadiya",
    "Ash-Shati",
    "An-Nahda",
    "An-Naeem",
    "An-Nozha",
    "Az-Zahraa",
    "As-Salamah",
    "Al Bawadi",
    "Ar-Rawda",
    "Al Safa",
    "Al Khalidiya",
    "Al Faysaliyah",
    "Al Andalus",
    "Al Aziziya",
    "Ar-Rihab",
    "Al Hamra",
    "Al Mosharafa",
    "Ar-Ruwais",
    "Ash-Sharafiya",
    "Bani Malik",
    "Al Woroud",
    "An-Naseem",
    "Al Hindawiya",
    "As-Saheifa",
    "Al Kandra",
  ],

  Dammam: [
    "Al Faisaliyah",
    "Ash-Shati",
    "Al Aziziyah",
    "Al Manar",
    "Al Rawdah",
    "Al Khobar",
    "Al Adamah",
    "Al Badiyah",
    "Madinat Al Umal",
    "Qasr Al Khalij",
    "Qurtubah",
    "King Faisal University District",
  ],

  Makkah: [
    "Al Faisaliyyah",
    "Ajyad",
    "Al Adl",
    "Al Buhayrat",
    "Al Ghassalah",
    "Al Hindawiyyah",
    "Al Iskan",
    "Al Jumaizah",
    "Al Maabda",
    "Al Muaisem",
    "Al Nuzha",
    "Al Rasaifah",
    "Al Shoqiyah",
    "Al Shubaikah",
    "Al Sulaimaniyyah",
    "Al Tundobawi",
    "Al Zuhur",
    "Al Kaakiyah",
    "Al Khaldiyah",
    "Al Shawqiyah",
    "King Fahad",
    "Batha Quraish",
    "Waly Al-Ahd",
  ],

  Madinah: [
    "Al Haram",
    "Quba",
    "Al Uyun",
    "Al Khalidiyyah",
    "Ar-Rayah",
    "Hadouda'",
    "Umm As-Suyouf",
    "Sadd Al-Ghaba",
    "As-Sahwa",
    "Wadi Al-Battana",
  ],

  Abha: [
    "Abha",
    "Abha Al Jadidah",
    "Ad Dabab",
    "Adwan",
    "Al 'Asim",
    "Al 'Ayn",
    "Al 'Azizah",
    "Al 'Azzah",
    "Al 'Utuf",
    "Al Adh Dhib",
    "Al Andalus",
  ],
};
